apiVersion: v1
kind: Service
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-kenzan
    tier: hello-kenzan
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-kenzan
        tier: hello-kenzan
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-kenzan:latest
        name: hello-kenzan
        ports:
        - containerPort: 80
          name: hello-kenzan
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kenzan
  labels:
    app: hello-kenzan-k8s
  annotations:
spec:
  rules:
  - host: hello-kenzan.mldigital.be
    http:
      paths:
        - path: /
          backend:
            serviceName: hello-kenzan
            servicePort: 80
